[program:hanabi-live]
directory=/root/hanabi-live
command=/root/hanabi-live/hanabi-live
environment=GOPATH=/root/go
redirect_stderr=true
stdout_logfile=/root/hanabi-live/logs/hanabi-live.log
; 100 MB x 50 = 5 GB total of logs
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=50
